name: 🔨 Build Test
on:
  pull_request:
  workflow_dispatch:


jobs:  
  build:
    name: Test Builds
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
    steps:
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.19

      - name: Check out code
        uses: actions/checkout@v3

      - name: Test example client
        run: go run .
        working-directory: example/client
